### ISSUE TITLE
Google Chrome marking the site Dangerous

### ISSUE THREAD

**Issue by mikeirvingweb** [AzureCosmosDB/azurecosmosdbconf#37]
Take a look at [https://azurecosmosdb.github.io/azurecosmosdbconf/](https://azurecosmosdb.github.io/azurecosmosdbconf/)

as redirected from [https://aka.ms/AzureCosmosDBConf](https://aka.ms/AzureCosmosDBConf)

Chrome is marking the site as dangerous
![image](https://github.com/AzureCosmosDB/azurecosmosdbconf/assets/79252299/0d0b5667-0c94-4d92-8562-7776db9219f7)

And clicking through from Gmail suggests it is a forgery
![image (1)](https://github.com/AzureCosmosDB/azurecosmosdbconf/assets/79252299/fbdb2616-a445-4a58-a057-6816b693ae82)

presumably due to the GitHub site being highly based on a known site (Azure)

I think it needs publishing to a proper URL to resolve this.

**Comment by jaydestro** [comment]
issue was resolved, was a false positive.
